import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { ShieldCheck, Lock, Eye, FileText, UserCheck, Smartphone, Globe, AlertTriangle } from 'lucide-react';

export default function PrivacyPolicy() {
  // Ensure the page opens at the top
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const sections = [
    {
      title: "1. Information We Collect",
      icon: <FileText className="w-5 h-5 text-indigo-600" />,
      content: (
        <div className="space-y-4">
          <p>To provide a secure, efficient, and personalized shopping experience, we collect specific categories of data. This collection is limited strictly to operational necessity.</p>
          
          <div className="pl-4 border-l-2 border-indigo-100">
            <h4 className="font-bold text-gray-900 mb-2">A. Personally Identifiable Information (PII)</h4>
            <p className="mb-2 text-gray-600">We collect data that you voluntarily provide to us when registering an account, updating your profile, or completing a checkout process:</p>
            <ul className="list-disc pl-5 text-gray-600 space-y-1">
              <li>Identity Data: Full legal name and account credentials.</li>
              <li>Contact Data: Valid mobile phone number and active email address.</li>
              <li>Geographical Data: Complete physical delivery and billing addresses (including Division, District, and Upazila specifications).</li>
            </ul>
          </div>

          <div className="pl-4 border-l-2 border-indigo-100">
            <h4 className="font-bold text-gray-900 mb-2">B. Financial and Transaction Data</h4>
            <p className="mb-2 text-gray-600">To facilitate secure order validation, we collect transactional records:</p>
            <ul className="list-disc pl-5 text-gray-600 space-y-3">
              <li>Mobile Banking Records: The specific mobile wallet number (e.g., bKash, Nagad, Rocket) utilized to execute a transfer, along with the corresponding unique Transaction ID (TxnID) generated by the mobile banking network.</li>
              <li className="list-none">
                <div className="bg-orange-50 border border-orange-100 rounded-xl p-4 mt-2">
                  <div className="flex items-center gap-2 mb-2">
                    <AlertTriangle className="w-5 h-5 text-orange-600" />
                    <span className="font-bold text-orange-900">Strict Exclusionary Policy</span>
                  </div>
                  <p className="text-orange-800 text-sm leading-relaxed">
                    AeroCart operates exclusively through secure, isolated mobile banking gateways. We do not solicit, intercept, process, or store credit card numbers, debit card credentials, bank account numbers, or related routing data.
                  </p>
                </div>
              </li>
            </ul>
          </div>

          <div className="pl-4 border-l-2 border-indigo-100">
            <h4 className="font-bold text-gray-900 mb-2">C. Technical and Usage Data</h4>
            <p className="text-gray-600">We automatically collect diagnostic information when you navigate our platform to ensure system stability: Device identifiers, internet protocol (IP) addresses, browser variants, operating system specifications, and real-time page interaction metrics.</p>
          </div>
        </div>
      )
    },
    {
      title: "2. Legal Basis and Purpose of Data Processing",
      icon: <UserCheck className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>We process your personal information under strict legal parameters, utilizing your data solely for the following business operations: Contractual Obligation (Processing payments, validating transaction logs, handling order fulfillments, logistics routing, and managing delivery dispatches), Customer Support (Resolving technical anomalies, managing product inquiries, and processing valid return or refund claims), and System Optimization (Monitoring platform infrastructure stability, mitigating high-frequency re-rendering anomalies, and preventing potential security breaches or malicious cart manipulations).</p>
      )
    },
    {
      title: "3. Data Retention Policy",
      icon: <Lock className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>We store your personal information only for as long as necessary to fulfill the operational purposes outlined in this policy, or to comply with mandatory statutory financial auditing regulations. Core transaction histories and account logs are maintained within an encrypted environment. If an account remains completely inactive for an extended period, or upon a formal user deletion request, the associated personal records will be securely purged or anonymized.</p>
      )
    },
    {
      title: "4. Third-Party Disclosures and System Integrations",
      icon: <Globe className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>We maintain a strict stance against commercializing user information. Your data will never be sold, leased, traded, or shared with external third parties for marketing purposes. Data is only disclosed to verified service providers under rigid confidentiality clauses to fulfill essential operations: Logistics Partners (Trusted courier and courier dispatch systems receive your name, address, and phone number solely to execute physical package delivery) and Analytical Tools (Aggregated, non-PII technical data may be processed by standard optimization services to evaluate site performance and loading speeds).</p>
      )
    },
    {
      title: "5. Data Security Architecture",
      icon: <ShieldCheck className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>We implement robust technical and administrative security measures to safeguard your information from unauthorized access, alteration, disclosure, or destruction: Encryption (Sensitive account data and user states are systematically protected using modern encryption protocols), Access Control (Internal access to user databases is heavily restricted to authorized administrative personnel subject to strict confidentiality agreements), and Vulnerability Monitoring (Regular internal system audits and diagnostic checkups are conducted to isolate performance or integrity risks before they affect the active environment).</p>
      )
    },
    {
      title: "6. User Rights and Data Control",
      icon: <Eye className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>In accordance with international data sovereignty principles, we grant you full transparency and autonomy over your personal information: Right to Access and Rectification (You possess the right to view, download, or correct your personal data at any moment via your account dashboard), Right to Erasure / The Right to be Forgotten (You may formally request the permanent deletion of your profile, transaction logs, and historical data from our active storage infrastructure), and Right to Restrict Processing (You have the right to object to specific technical data processing or opt-out of secondary informational communications).</p>
      )
    },
    {
      title: "7. Children's Privacy Compliance",
      icon: <UserCheck className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>AeroCart operates as a general audience commercial platform. Our services are strictly intended for individuals who are legally recognized as adults (18 years of age or older). We do not knowingly or intentionally collect personal identifiable information from minors under the age of 18. If we identify that a minor's information has been inadvertently recorded, it will be immediately and permanently expunged from our servers.</p>
      )
    },
    {
      title: "8. Cookies and Tracking Mechanisms",
      icon: <Smartphone className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>Our platform utilizes standard browser cookies and local storage tokens to optimize technical efficiency: Essential Cookies (Necessary to sustain your active authentication state, preserve the contents of your Cart Drawer, and prevent navigation flickering during page transitions) and Performance Cookies (Employed to accelerate page responsiveness and cache recurring structural assets). You can adjust your browser settings to decline cookies; however, doing so may disable core features of the e-commerce checkout workflow.</p>
      )
    },
    {
      title: "9. Amendments to This Privacy Policy",
      icon: <FileText className="w-5 h-5 text-indigo-600" />,
      content: (
        <p>We reserve the legal right to revise, update, or rewrite this Privacy Policy at our discretion to match expanding features or shifting legal environments. The "Last Updated" timestamp at the apex of this document will reflect the most recent modification. Continual engagement with our platform after an official revision has been published denotes your proactive acceptance of the updated terms.</p>
      )
    },
    {
      title: "10. Contact and Legal Inquiries",
      icon: <Mail className="w-4 h-4 text-indigo-600" />,
      content: (
        <div className="bg-gray-50 rounded-xl p-6 border border-gray-100">
          <p className="mb-4">For any compliance queries, requests regarding your individual user rights, or to submit a formal data deletion directive, please reach out to our administration at:</p>
          <div className="space-y-1 text-sm">
            <p className="flex items-center gap-2">
              <span className="font-bold text-gray-900 w-24">Email:</span>
              <a href="mailto:support@aerocart.com" className="text-indigo-600 hover:underline">support@aerocart.com</a>
            </p>
            <p className="flex items-center gap-2">
              <span className="font-bold text-gray-900 w-24">Corporate:</span>
              <span className="text-gray-600">AeroCart Platform Operations</span>
            </p>
          </div>
        </div>
      )
    }
  ];

  return (
    <div className="bg-gray-50 min-h-screen pb-20">
      {/* Hero Header */}
      <section className="relative w-full overflow-hidden bg-[#2d1b69] pt-24 pb-32 md:pt-32 md:pb-48">
        {/* Abstract smooth lines & blurred assets */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-indigo-500/20 rounded-full blur-[120px] -translate-y-1/2 translate-x-1/3"></div>
          <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-purple-600/20 rounded-full blur-[100px] translate-y-1/3 -translate-x-1/4"></div>
          <svg className="absolute inset-0 w-full h-full opacity-10" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path d="M0,50 Q25,30 50,50 T100,50" fill="none" stroke="white" strokeWidth="0.5" />
            <path d="M0,60 Q25,40 50,60 T100,60" fill="none" stroke="white" strokeWidth="0.5" />
          </svg>
        </div>
        
        <div className="max-w-4xl mx-auto text-center relative z-10 px-4">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-white text-xs font-bold uppercase tracking-wider mb-6 border border-white/20 backdrop-blur-sm"
          >
            <ShieldCheck className="w-3 h-3" />
            Legal & Compliance
          </motion.div>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-6xl font-extrabold text-white mb-6 tracking-tight leading-tight"
          >
            Privacy Policy
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-indigo-100 text-lg md:text-xl max-w-2xl mx-auto leading-relaxed font-medium"
          >
            AeroCart is deeply committed to maintaining the highest standards of data protection, user privacy, and legal transparency.
          </motion.p>
        </div>
      </section>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 -mt-16 md:-mt-24 relative z-20">
        <motion.div 
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2 }}
          className="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden"
        >
          <div className="p-8 md:p-12">
            <div className="flex items-center justify-between mb-12 pb-6 border-b border-gray-100">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center">
                  <Lock className="w-6 h-6 text-indigo-600" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-gray-900">Legal Statement</h2>
                  <p className="text-sm text-gray-500">How we manage your data</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Last Updated</p>
                <p className="text-sm font-bold text-indigo-600">July 2026</p>
              </div>
            </div>

            <div className="prose prose-indigo max-w-none">
              <p className="text-gray-600 leading-relaxed mb-8">
                AeroCart ("we," "our," or "us") operates the AeroCart e-commerce platform. We are deeply committed to maintaining the highest standards of data protection, user privacy, and legal transparency. This Privacy Policy serves as a comprehensive legal statement outlining how we collect, process, secure, and manage your personal identifiable information (PII) in compliance with international data protection frameworks and local regulations.
              </p>
              
              <div className="bg-indigo-50/50 rounded-2xl p-6 mb-12 border border-indigo-100">
                <p className="text-indigo-900 font-medium italic text-center">
                  "By accessing our services, creating an account, or making a purchase on AeroCart, you explicitly consent to the practices described in this policy."
                </p>
              </div>

              <div className="space-y-12">
                {sections.map((section, index) => (
                  <div key={index} className="scroll-mt-24">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center">
                        {section.icon}
                      </div>
                      <h3 className="text-xl font-bold text-gray-900 tracking-tight">
                        {section.title}
                      </h3>
                    </div>
                    <div className="text-gray-600 leading-relaxed">
                      {section.content}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
          
          <div className="bg-gray-50 px-8 py-6 border-t border-gray-100 flex items-center justify-center">
            <p className="text-xs text-gray-400 text-center font-medium">
              &copy; {new Date().getFullYear()} AeroCart Platform Operations. Standard International Legal Framework Applied.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

function Mail(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}
