import { Product, Category } from "./types";

export const categories: Category[] = [
  {
    id: "c1",
    name: "Electronics & Gadget",
    icon: "smartphone",
    slug: "electronics-gadget",
    itemCount: 12453,
    color: "text-blue-500 group-hover:text-blue-600",
    bgColor: "bg-blue-50 group-hover:bg-blue-100",
    subcategories: ["Smart Devices", "Audio & Sound", "Tech Accessories"],
  },
  {
    id: "c2",
    name: "Personal Care",
    icon: "sparkles",
    slug: "personal-care",
    itemCount: 15420,
    color: "text-pink-500 group-hover:text-pink-600",
    bgColor: "bg-pink-50 group-hover:bg-pink-100",
    subcategories: ["Grooming Tools", "Skincare & Hygiene", "Hair & Body Care"],
  },
  {
    id: "c3",
    name: "Appliances",
    icon: "refrigerator",
    slug: "appliances",
    itemCount: 8932,
    color: "text-slate-600 group-hover:text-slate-700",
    bgColor: "bg-slate-100 group-hover:bg-slate-200",
    subcategories: [
      "Kitchen Appliances",
      "Home Comfort",
      "Smart Home Automation",
    ],
  },
  {
    id: "c4",
    name: "Food & Grocery",
    icon: "shopping-basket",
    slug: "food-grocery",
    itemCount: 3201,
    color: "text-green-500 group-hover:text-green-600",
    bgColor: "bg-green-50 group-hover:bg-green-100",
    subcategories: ["Daily Essentials", "Snacks & Beverages", "Packaged Foods"],
  },
  {
    id: "c5",
    name: "Fashion",
    icon: "shirt",
    slug: "fashion",
    itemCount: 45210,
    color: "text-purple-500 group-hover:text-purple-600",
    bgColor: "bg-purple-50 group-hover:bg-purple-100",
    subcategories: [
      "Men's Apparel",
      "Women's Collection",
      "Footwear & Accessories",
    ],
  },
  {
    id: "c6",
    name: "Health Care",
    icon: "heart-pulse",
    slug: "health-care",
    itemCount: 6734,
    color: "text-red-500 group-hover:text-red-600",
    bgColor: "bg-red-50 group-hover:bg-red-100",
    subcategories: [
      "Supplements & Nutrition",
      "Medical Devices",
      "OTC & Wellness",
    ],
  },
  {
    id: "c7",
    name: "Baby & Kids",
    icon: "baby",
    slug: "baby-kids",
    itemCount: 4120,
    color: "text-amber-500 group-hover:text-amber-600",
    bgColor: "bg-amber-50 group-hover:bg-amber-100",
    subcategories: ["Baby Care & Hygiene", "Kids' Fashion", "Toys & Learning"],
  },
  {
    id: "c8",
    name: "Hot Offers",
    icon: "flame",
    slug: "hot-offers",
    itemCount: 1350,
    color: "text-orange-500 group-hover:text-orange-600",
    bgColor: "bg-orange-50 group-hover:bg-orange-100",
    subcategories: ["Mega Discounts", "Combo Deals", "Clearance Sale"],
  },
];

export const flashSaleProducts: Product[] = [
  {
    id: "p1",
    name: "Wireless Noise Cancelling Earbuds Pro",
    price: 89.99,
    originalPrice: 149.99,
    discount: 40,
    rating: 4.8,
    reviews: 1245,
    image:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400",
    category: "Electronics & Gadget",
    subcategory: "Audio & Sound",
    stock: 45,
    vendor: "TechGlobal",
    isFlashSale: true,
    colors: ["Black", "White"],
    variants: [],
  },
  {
    id: "p2",
    name: "Minimalist Leather Smart Watch",
    price: 129.5,
    originalPrice: 199.0,
    discount: 35,
    rating: 4.6,
    reviews: 892,
    image:
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=400",
    category: "Electronics & Gadget",
    subcategory: "Smart Devices",
    stock: 12,
    vendor: "WristTech",
    isFlashSale: true,
    colors: ["Black", "Silver"],
    variants: [],
  },
  {
    id: "p3",
    name: "Ergonomic Office Chair with Lumbar Support",
    price: 159.0,
    originalPrice: 249.0,
    discount: 36,
    rating: 4.5,
    reviews: 430,
    image:
      "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=400",
    category: "Appliances",
    subcategory: "Home Comfort",
    stock: 8,
    vendor: "HomeComfort",
    isFlashSale: true,
    colors: ["Black", "Classic Gray"],
    variants: [],
  },
  {
    id: "p4",
    name: "Premium Skincare Travel Kit",
    price: 45.0,
    originalPrice: 75.0,
    discount: 40,
    rating: 4.9,
    reviews: 2150,
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=400",
    category: "Personal Care",
    subcategory: "Skincare & Hygiene",
    stock: 150,
    vendor: "GlowCosmetics",
    isFlashSale: true,
    colors: [],
    variants: [],
  },
];

export const trendingProducts: Product[] = [
  {
    id: "t1",
    name: "Ultra HD 4K Action Camera",
    price: 299.99,
    rating: 4.7,
    reviews: 512,
    image:
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&q=80&w=400",
    category: "Electronics & Gadget",
    subcategory: "Smart Devices",
    stock: 25,
    vendor: "ActionGear",
    colors: ["Black", "Silver"],
    variants: ["64GB", "128GB"],
  },
  {
    id: "t2",
    name: "Men's Casual Canvas Sneakers",
    price: 54.9,
    rating: 4.4,
    reviews: 128,
    image:
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=400",
    category: "Fashion",
    subcategory: "Men's Apparel",
    stock: 100,
    vendor: "UrbanWalk",
    colors: ["Maroon", "Navy Blue"],
    variants: ["S", "M", "L", "XL"],
  },
  {
    id: "t6",
    name: "Premium Leather Minimalist Wallet",
    price: 29.99,
    rating: 4.8,
    reviews: 512,
    image:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=400",
    category: "Fashion",
    subcategory: "Footwear & Accessories",
    stock: 140,
    vendor: "LeatherCraft",
    colors: ["Brown", "Black", "Tan"],
    variants: [],
  },
  {
    id: "t3",
    name: "Ceramic Essential Oil Diffuser",
    price: 34.0,
    rating: 4.8,
    reviews: 3045,
    image:
      "https://images.unsplash.com/photo-1602928321679-560bb453f190?auto=format&fit=crop&q=80&w=400",
    category: "Appliances",
    subcategory: "Home Comfort",
    stock: 50,
    vendor: "ZenHome",
    colors: ["White", "Light Wood"],
    variants: ["300ml", "500ml"],
  },
  {
    id: "t4",
    name: "Professional Chef Knife Set",
    price: 120.0,
    originalPrice: 150.0,
    discount: 20,
    rating: 4.9,
    reviews: 672,
    image:
      "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&q=80&w=400",
    category: "Appliances",
    subcategory: "Kitchen Appliances",
    stock: 18,
    vendor: "CulinaryMaster",
    colors: ["Silver", "Black"],
    variants: [],
  },
  {
    id: "t5",
    name: "Wireless Charging Power Bank",
    price: 49.99,
    rating: 4.5,
    reviews: 890,
    image:
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&q=80&w=400",
    category: "Electronics & Gadget",
    subcategory: "Tech Accessories",
    stock: 200,
    vendor: "TechGlobal",
    colors: ["Black", "Space Gray"],
    variants: [],
  },
];

export const products: Product[] = [...flashSaleProducts, ...trendingProducts];

